package io.github.cmeredit.nbt.tags

// I'm sorry, but I don't want to deal with adding an `UnnamedTag` trait just for this
// one tag type which I never intend to use anyway
//
// Just give the tags in the payload an empty or autogenerated name (e.g., name of the list tag + payload index)
// This makes ListTags bulkier. If it really becomes a performance issue for you, bug me and I'll
// stop being lazy about it (or, feel free to fix it and make a pull request)
case class ListTag(name: String, payload: Vector[Tag]) extends Tag {
  type A = Vector[Tag]

  override val typeName: String = Identifiers.TypeNames.list
}
